### ISSUE TITLE
Email error

### ISSUE THREAD

**Issue by meetgyn** [Aravindha1234u/Probe_spider#3]
Enter the Email Address (Eg: test@gmail.com):xxxxxxx@gmail.com
[+] Data Breaching .....

sh: 1: h8mail: not found
Traceback (most recent call last):
   Main.py file, line 55, in <module>
     main ()
   Main.py file, line 53, in main
     switcher [ch] ()
   File "/opt/osint/Probe_spider/maildb.py", line 13, in maildb
     f = open ("/ root / Downloads / osint / src / output.csv", "r")
FileNotFoundError: [Errno 2] No such file or directory: '/root/Downloads/osint/src/output.csv'
root @ Lab1: / opt / osint / Probe_spider #

These files were created inside Root

**Comment by Aravindha1234u** [comment]
@meetgyn can you try the latest version of reconspider

[Repository](https://github.com/bhavsec/reconspider)

We have merged the tool and released a update.
